### PR TITLE
Fix an error where dsc-datatool would choke on utf8 data

### PR DESCRIPTION
**Pull request by jblt-sidn**

### CODE REVIEW

**Comment by jelu** [comment]
I'm unsure forcing encoding here is the right way.

Python's [builtin `open()`](https://docs.python.org/3/library/functions.html#open) will use the systems encoding, did you have correct `LC_*` set up?

**Comment by jelu** [comment]
@jblt-sidn can you post the error / traceback you got also?

**Comment by jblt-sidn** [comment]
@jelu We were wondering why we had to force utf8 encoding also. Will look into system encoding but we feel dsc-datatool may benefit from enabling utf-8 encoding _explicitly_ so other people don't fall into the same trap.

Example stack trace:
`2023-05-03 00:01:03,458 WARNING __init__: Output <dsc_datatool.output.influxdb.InfluxDB object at 0x7f2597ae01d0> failed: 'ascii' codec can't encode character '\xe9' in position 91: ordinal not in range(128)
2023-05-03 00:01:03,459 WARNING __init__:   File "/usr/lib/python3.6/site-packages/dsc_datatool/__init__.py", line 301, in _process
    output.process(datasets)

2023-05-03 00:01:03,459 WARNING __init__:   File "/usr/lib/python3.6/site-packages/dsc_datatool/output/influxdb.py", line 99, in process
    _process(tags, timestamp, d, self.fh)

2023-05-03 00:01:03,459 WARNING __init__:   File "/usr/lib/python3.6/site-packages/dsc_datatool/output/influxdb.py", line 39, in _process
    _process(tags, timestamp, d2, fh)

2023-05-03 00:01:03,459 WARNING __init__:   File "/usr/lib/python3.6/site-packages/dsc_datatool/output/influxdb.py", line 49, in _process
    print('%s%s value=%s %s' % (tags, _val(k), v, timestamp), file=fh)

2023-05-03 00:01:03,830 WARNING __init__: Output <dsc_datatool.output.influxdb.InfluxDB object at 0x7fe1a7b39358> failed: 'ascii' codec can't encode character '\xe9' in position 91: ordinal not in range(128)
2023-05-03 00:01:03,830 WARNING __init__:   File "/usr/lib/python3.6/site-packages/dsc_datatool/__init__.py", line 301, in _process
    output.process(datasets)`

**Comment by jelu** [comment]
Fixed in #104

**Pull request closed without merging**
